In [2]:
#Library use to import data

import pandas as pd

In [3]:
#Library use for calculation

import numpy as np

In [4]:
# Loading the data

pd.read_csv('cars24data.csv')

,Car_model,Car_Name,Price,Ratings_out_of_5,city_code,Km_covered,Owner,Fuel_Type,Transmission,RTO_code,Insurance,Insurance_Type,Insurance_Type.3
0,2010,Maruti Alto LXI,174699,4.0,3686,34854,First,Petrol,MANUAL,AP09,NaN,Insurance,Expired
1,2013,Maruti Wagon R 1.0 VXI,333999,4.2,3686,39541,Second,Petrol,MANUAL,AP28,06-08-21 0:00,Comp,NaN
2,2014,Maruti Wagon R 1.0 VXI,353199,4.3,3686,23233,Second,Petrol,MANUAL,AP28,28-04-21 0:00,Comp,NaN
3,2013,Hyundai Eon D LITE PLUS,237899,4.4,3686,27748,First,Petrol,MANUAL,AP13,01-01-22 0:00,Comp,NaN
4,2017,Hyundai Eon ERA PLUS,300699,4.4,3686,12238,Second,Petrol,MANUAL,TS10,NaN,Expired,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32153,2008,Ford Fiesta 1.6 ZXI,150000,3.4,769,95792,Third,Petrol,MANUAL,CH04,NaN,Insurance,Expired
32154,2015,Chevrolet Beat LS DIESEL,250000,3.5,769,54505,Second,Diesel,MANUAL,PB13,NaN,Insurance,Expired
32155,2008,Ford Endeavour XLT TDCI 4X2,500000,3.6,769,161322,Second,Diesel,MANUAL,HR03,NaN,Insurance,Expired
32156,2016,Maruti Swift Dzire VDI ABS,600000,4.7,769,52006,First,Diesel,NaN,PB65,27-10-19 0:00,Zero,Depreciation
32157,2007,Mercedes Benz C Class 220 CDI AT,484000,3.8,769,88818,Second,Diesel,AUTOMATIC,PB65,28-11-19 0:00,Comprehensive,NaN

In [5]:
#storing data in df variable

df = pd.read_csv('cars24data.csv')

In [6]:
#checking the data

df.head(1)

,Car_model,Car_Name,Price,Ratings_out_of_5,city_code,Km_covered,Owner,Fuel_Type,Transmission,RTO_code,Insurance,Insurance_Type,Insurance_Type.3
0,2010,Maruti Alto LXI,174699,4.0,3686,34854,First,Petrol,MANUAL,AP09,NaN,Insurance,Expired

In [7]:
#dropping not useful columns

df.drop(columns=['Car_Name', 'RTO_code', 'Insurance', 'Insurance_Type', 'Insurance_Type.3'], inplace=True)

In [8]:
#checking the data

df.head(1)

,Car_model,Price,Ratings_out_of_5,city_code,Km_covered,Owner,Fuel_Type,Transmission
0,2010,174699,4.0,3686,34854,First,Petrol,MANUAL

In [ ]:
#dropping null values

df.dropna(inplace=True)

In [11]:
#Removing duplicates

df.duplicated().sum()

np.int64(0)

In [14]:
#checking columns and Rows

df.shape

(32158, 8)

In [15]:
#defing the Price 
# 1 price is above median 
# 0 if below

median_price = df['Price'].median()
df['Price_Class'] = (df['Price'] > median_price).astype(int)

In [18]:
#checking the data

df.head(1)

,Car_model,Price,Ratings_out_of_5,city_code,Km_covered,Owner,Fuel_Type,Transmission,Price_Class
0,2010,174699,4.0,3686,34854,First,Petrol,MANUAL,0

In [20]:
#dropping the price columns we already categorized the price

df.drop(columns=['Price'], inplace=True)

In [21]:
#checking the data

df.head(1)

,Car_model,Ratings_out_of_5,city_code,Km_covered,Owner,Fuel_Type,Transmission,Price_Class
0,2010,4.0,3686,34854,First,Petrol,MANUAL,0

In [22]:
# Storing  value  (X) 
# pd.get_dummies  (covertign the value to 0 and  1)
# df.drop         (use to drop the columns)
# axis=1          (Use to drop the whole column)
# drop_first=True (avoid multicollinearity)
# y = Target Variable

X = pd.get_dummies(df.drop('Price_Class', axis=1), drop_first=True) 
y = df['Price_Class']

In [27]:
#checking the data

X.shape, y.shape

((32158, 19), (32158,))

In [30]:
#converting all values to 0 and 1

X = X.astype(int)

In [33]:
X.head(1)

,Car_model,Ratings_out_of_5,city_code,Km_covered,Owner_Fifth,Owner_First,Owner_Fourth,Owner_Ninth,Owner_Second,Owner_Seventh,Owner_Sixth,Owner_Tenth,Owner_Third,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Fuel_Type_Petrol + CNG,Fuel_Type_Petrol + LPG,Transmission_MANUAL
0,2010,4,3686,34854,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1

In [34]:
# Train Test Split

#importing Library
from sklearn.model_selection import  train_test_split

#Splitting Data in to X and y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [35]:
# StandardScaler

#importing Libraray
from sklearn.preprocessing import StandardScaler

#Applying
sc = StandardScaler() 
X_train = sc.fit_transform(X_train)                   
X_test = sc.transform(X_test)

In [36]:
X_train

array([[-0.97243231, -0.95931128,  0.50653151, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [-0.75063453,  0.63991384,  1.15770705, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [ 1.02374772,  0.63991384,  0.50653151, ..., -0.2219683 ,
        -0.12551469, -2.19883678],
       ...,
       [ 1.46734329,  0.63991384,  1.15770705, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [-1.19423009, -0.95931128,  1.15770705, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [-0.52883675, -0.95931128,  0.50653151, ..., -0.2219683 ,
        -0.12551469,  0.45478592]], shape=(25726, 19))

In [37]:
X_test

array([[-0.52883675, -0.95931128,  1.8088826 , ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [-0.08524118, -0.95931128, -0.76271975, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [ 0.1365566 , -0.95931128, -0.48391731, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       ...,
       [ 1.02374772,  0.63991384, -1.34514948, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [ 0.58015216,  0.63991384,  1.15770705, ..., -0.2219683 ,
        -0.12551469,  0.45478592],
       [ 0.35835438,  0.63991384,  1.15770705, ..., -0.2219683 ,
        -0.12551469,  0.45478592]], shape=(6432, 19))

Training The ANN Model

In [38]:
#Library to import to Train the ANN Model

import tensorflow as tf  
import keras             
from keras.models import Sequential 
from keras.layers import Dense

In [39]:
#storing in ann variable

ann = Sequential()

In [40]:
# Input layer 
ann.add(Dense(input_dim=X_train.shape[1], units=6, kernel_initializer='uniform', activation='relu')) 

# Hidden layer
ann.add(Dense(units=6, kernel_initializer='uniform', activation='relu')) 

# Output layer
ann.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

C:\Users\TOUFIQ\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
# Compiling 

ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [42]:
# Training the ANN on the Training set

ann.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7988 - loss: 0.4527
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8338 - loss: 0.3630
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8349 - loss: 0.3605
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8354 - loss: 0.3595
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8362 - loss: 0.3587
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8342 - loss: 0.3580
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8358 - loss: 0.3571
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8364 - loss: 0.3562
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8367 - loss: 0.3563
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8362 - loss: 0.3556
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8369 - loss: 0.3553
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8364 - loss: 0.3549
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8366 - loss: 0.3546
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8366 - loss: 0.3543
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8367 - loss: 0.3540
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8362 - loss: 0.3540
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8378 - loss: 0.3535
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8374 - loss: 0.3536
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8383 - loss: 0.3535
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8385 - loss: 0.3531
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8367 - loss: 0.3532
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8382 - loss: 0.3531
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8375 - loss: 0.3529
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8372 - loss: 0.3528
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8374 - loss: 0.3529
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8380 - loss: 0.3528
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8385 - loss: 0.3527
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8383 - loss: 0.3526
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8388 - loss: 0.3528
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8382 - loss: 0.3523
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8368 - loss: 0.3525
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8387 - loss: 0.3526
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8385 - loss: 0.3522
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8393 - loss: 0.3522
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8382 - loss: 0.3520
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8377 - loss: 0.3521
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8378 - loss: 0.3521
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8383 - loss: 0.3522
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8376 - loss: 0.3521
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8379 - loss: 0.3522
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8376 - loss: 0.3521
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8388 - loss: 0.3519
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8380 - loss: 0.3521
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8387 - loss: 0.3521
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8381 - loss: 0.3522
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8374 - loss: 0.3520
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8371 - loss: 0.3517
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8386 - loss: 0.3520
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8383 - loss: 0.3519
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8386 - loss: 0.3517
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8370 - loss: 0.3520
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8382 - loss: 0.3519
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8379 - loss: 0.3518
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8382 - loss: 0.3517
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8380 - loss: 0.3518
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8383 - loss: 0.3518
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8384 - loss: 0.3517
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8381 - loss: 0.3517
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8376 - loss: 0.3518
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8376 - loss: 0.3516
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8386 - loss: 0.3518
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8385 - loss: 0.3517
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8383 - loss: 0.3518
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8382 - loss: 0.3515
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8389 - loss: 0.3516
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8378 - loss: 0.3517
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8382 - loss: 0.3517
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8375 - loss: 0.3514
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8393 - loss: 0.3515
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8387 - loss: 0.3514
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8387 - loss: 0.3514
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8387 - loss: 0.3515
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8381 - loss: 0.3514
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8373 - loss: 0.3514
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8378 - loss: 0.3514
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8390 - loss: 0.3514
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8379 - loss: 0.3511
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8377 - loss: 0.3514
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8381 - loss: 0.3515
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8381 - loss: 0.3513
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8388 - loss: 0.3513
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8385 - loss: 0.3514
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8387 - loss: 0.3513
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8382 - loss: 0.3512
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8376 - loss: 0.3511
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8384 - loss: 0.3511
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8388 - loss: 0.3508
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8379 - loss: 0.3512
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8378 - loss: 0.3511
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8391 - loss: 0.3510
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8385 - loss: 0.3510
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8384 - loss: 0.3511
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8378 - loss: 0.3510
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8379 - loss: 0.3508
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8390 - loss: 0.3509
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8388 - loss: 0.3511
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8381 - loss: 0.3508
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8389 - loss: 0.3508
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8378 - loss: 0.3509
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8391 - loss: 0.3508

In [ ]:
y_pred

In [ ]:
Evaluation

In [43]:
# Importing confusion Matrix and Accuracy Score 

from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
# Model predictions

y_pred = ann.predict(X_test) 
y_pred = (y_pred > 0.5)

In [50]:
#checking the Accuracy

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Test Accuracy: 0.8439054726368159
Confusion Matrix:
 [[2637  575]
 [ 429 2791]]

In [ ]:
________END_________